---
title: "Lab 02 - Global plastic waste"
author: "SSR: Yanyi Chen, Ziwei Huang, Shiliang Su, Nanshuyuan Zhang, Peiheng Liu and Pinzhe Zhao"
date: "`r Sys.Date()`"
output: html_document
---

### Load packages and data

```{r load-packages, message = FALSE, warning=FALSE}
library(tidyverse)
library(readxl)
```


## Load & join data sets

```{r load-data, message = FALSE}
# Member 2 (pair 1) write code to load File 1 data here:
library(readxl)

un_country_region <- read_excel("~/lab02/data/UN_country_region.xlsx")






# Member 4 (pair 2) write code to load File 2 data here:
library(readr)
un_country_population <- read_tsv("~/lab02/data/UN_country_population.tsv")


# Member 6 (pair 3) write code to load File 3 data here:
per_capita_ocean_plastic_waste <- read_csv("~/lab02/data/per-capita-ocean-plastic-waste.txt")


# Member 1 (pair 1) write code to load File 4 data here:


mismanged_plastic_waste_per_capita <- read_csv("~/lab02/data/mismanaged-plastic-waste-per-capita.csv")

```



```{r join-data, message = FALSE}
# Member 2 (pair 1) write code to create object 'plastic_data_all':




# Member 4 (pair 2) write code to join your data to 'plastic_data_all':




# Member 6 (pair 3) write code to join your data to 'plastic_data_all':




# Member 1 (pair 1) write code to join your data to 'plastic_data_all':



```


```{r print-data, message = FALSE}
# Member 2 (pair 1) adds code here to view the first 10 rows of 'plastic_data_all'



```



## Exercises

### Ex 1.

```{r Ex1, message = FALSE}
# Write your code here to answer exercise 1



```



### Ex 2.

```{r Ex2, message = FALSE}
# Write your code here to answer exercise 2



```


### Ex 3.

```{r Ex3, message = FALSE}
# Write your code here to answer exercise 3



```


### Ex 4.

```{r Ex4, message = FALSE}
# Write your code here to answer exercise 4



```
